// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "65643e9e852b477c001d8056c6542a6e40cf3599ebc571025d08c74c8b11c60c")
