// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = newAsset("runtime-security.c", "8d9dd913064d7e5a322ce035f5f32e52bf849e2a2d808a431b1dce87922f9f1e")
