// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "1c989e5c935ce0eb85cb8943d35192f973bfe525de598da2fecb9d30dd646c68")
