// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "57daf5dc29ea94456c6cb8a91c6781c71aa3bc8f00f50c2d1646da0bf76f4bde")
