// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "1ada51321e7c0c56a5789b2ceb76abd5db1281b902030e7ff2e20fab8ecc23f5")
